version: "3"
services:
  bot:
    build: .
    restart: always
    entrypoint: python3 -u /app/bot.py
    volumes:
      - "./:/app"
    environment:
      - "JISHAKU_HIDE=True"
      - "JISHAKU_NO_UNDERSCORE=True"
